// Mock data for communities and posts
export interface Community {
  id: string;
  name: string;
  description: string;
  memberCount: number;
  slug: string;
  color: string;
  region: string;
  state?: string; // Optional, only for US communities
}

export interface Post {
  id: string;
  caption: string;
  author: string;
  timestamp: string;
  reactions: { 
    heart: number; 
    thumbsUp: number; 
    thinking: number; 
    eyes: number;
    hope?: number;
    hug?: number;
    grateful?: number;
  };
  commentCount: number;
  anonymous: boolean;
  images: string[];
  videos: any[];
  community: string;
  comments: any[];
}

export const mockCommunities: Community[] = [
  {
    id: "1",
    name: "PMS Support",
    description: "A supportive community for people managing Phelan-McDermid Syndrome",
    memberCount: 850,
    slug: "pms-support",
    color: "bg-blue-100 text-blue-800",
    region: "United States",
    state: "California",
  },
  {
    id: "2",
    name: "Rett Syndrome Community",
    description: "Connecting families and individuals affected by Rett Syndrome",
    memberCount: 620,
    slug: "rett-syndrome-support",
    color: "bg-purple-100 text-purple-800",
    region: "United States",
    state: "Texas",
  },
  {
    id: "3",
    name: "Fragile X Forum",
    description: "Discussions and resources for Fragile X Syndrome",
    memberCount: 710,
    slug: "fragile-x-support",
    color: "bg-green-100 text-green-800",
    region: "Europe",
  },
  {
    id: "4",
    name: "Angelman Syndrome Connect",
    description: "Support and information for Angelman Syndrome",
    memberCount: 480,
    slug: "angelman-support",
    color: "bg-yellow-100 text-yellow-800",
    region: "United States",
    state: "New York",
  },
  {
    id: "5",
    name: "Prader-Willi Life",
    description: "Navigating life with Prader-Willi Syndrome",
    memberCount: 350,
    slug: "prader-willi-support",
    color: "bg-orange-100 text-orange-800",
    region: "United States",
    state: "Florida",
  },
  {
    id: "6",
    name: "Down Syndrome Network",
    description: "A community for individuals and families with Down Syndrome",
    memberCount: 1500,
    slug: "down-syndrome-support",
    color: "bg-pink-100 text-pink-800",
    region: "United States",
    state: "Illinois",
  },
  {
    id: "7",
    name: "Cystic Fibrosis Warriors",
    description: "Fighting CF together, sharing experiences and support",
    memberCount: 920,
    slug: "cystic-fibrosis-support",
    color: "bg-teal-100 text-teal-800",
    region: "Asia",
  },
  {
    id: "8",
    name: "Sickle Cell Strong",
    description: "Empowering those with Sickle Cell Anemia",
    memberCount: 550,
    slug: "sickle-cell-anemia-support",
    color: "bg-red-100 text-red-800",
    region: "United States",
    state: "Georgia",
  },
  {
    id: "9",
    name: "Huntington's Hope",
    description: "Support and research for Huntington's Disease",
    memberCount: 280,
    slug: "huntingtons-disease-support",
    color: "bg-indigo-100 text-indigo-800",
    region: "Europe",
  },
  {
    id: "10",
    name: "SMA Family Support",
    description: "Connecting families affected by Spinal Muscular Atrophy",
    memberCount: 400,
    slug: "sma-support",
    color: "bg-lime-100 text-lime-800",
    region: "United States",
    state: "Arizona",
  },
  {
    id: "11",
    name: "Batten Disease Alliance",
    description: "A community for support and advocacy for Batten Disease",
    memberCount: 180,
    slug: "batten-disease-support",
    color: "bg-rose-100 text-rose-800",
    region: "United States",
    state: "Ohio",
  },
  {
    id: "12",
    name: "Tay-Sachs Connect",
    description: "Support and resources for Tay-Sachs Disease families.",
    memberCount: 120,
    slug: "tay-sachs-support",
    color: "bg-cyan-100 text-cyan-800",
    region: "South America",
  },
  {
    id: "13",
    name: "Gaucher Disease Community",
    description: "A place for individuals and families with Gaucher Disease.",
    memberCount: 200,
    slug: "gaucher-disease-support",
    color: "bg-amber-100 text-amber-800",
    region: "United States",
    state: "Washington",
  },
  {
    id: "14",
    name: "MSUD Support Group",
    description: "Connecting those affected by Maple Syrup Urine Disease.",
    memberCount: 90,
    slug: "msud-support",
    color: "bg-fuchsia-100 text-fuchsia-800",
    region: "United States",
    state: "Michigan",
  },
  {
    id: "15",
    name: "PKU Life",
    description: "Living with Phenylketonuria: tips, recipes, and support.",
    memberCount: 300,
    slug: "pku-support",
    color: "bg-emerald-100 text-emerald-800",
    region: "Europe",
  },
  {
    id: "16",
    name: "General Genetic Conditions",
    description: "A broad community for various genetic conditions",
    memberCount: 2500,
    slug: "general-genetic-conditions",
    color: "bg-gray-100 text-gray-800",
    region: "United States",
    state: "Colorado",
  },
  {
    id: "17",
    name: "Turner Syndrome Support NY",
    description: "New York-based support for Turner Syndrome families",
    memberCount: 340,
    slug: "turner-syndrome-ny",
    color: "bg-violet-100 text-violet-800",
    region: "United States",
    state: "New York",
  },
  {
    id: "18",
    name: "Autism Spectrum Texas",
    description: "Texas community for Autism Spectrum Disorder support",
    memberCount: 1200,
    slug: "autism-spectrum-texas",
    color: "bg-blue-100 text-blue-800",
    region: "United States",
    state: "Texas",
  },
  {
    id: "19",
    name: "Cerebral Palsy UK",
    description: "United Kingdom support network for Cerebral Palsy",
    memberCount: 680,
    slug: "cerebral-palsy-uk",
    color: "bg-green-100 text-green-800",
    region: "Europe",
  },
  {
    id: "20",
    name: "Muscular Dystrophy Brazil",
    description: "Brazilian community for Muscular Dystrophy awareness",
    memberCount: 420,
    slug: "muscular-dystrophy-brazil",
    color: "bg-yellow-100 text-yellow-800",
    region: "South America",
  },
  {
    id: "21",
    name: "Thalassemia Support Asia",
    description: "Asian network for Thalassemia patients and families",
    memberCount: 750,
    slug: "thalassemia-asia",
    color: "bg-red-100 text-red-800",
    region: "Asia",
  },
  {
    id: "22",
    name: "Klinefelter Syndrome Florida",
    description: "Florida-based support for Klinefelter Syndrome",
    memberCount: 180,
    slug: "klinefelter-florida",
    color: "bg-cyan-100 text-cyan-800",
    region: "United States",
    state: "Florida",
  },
];

export const basePosts: Post[] = [
  {
    id: "1",
    caption: "It's been a challenging road since our daughter's Phelan-McDermid Syndrome diagnosis. Looking for others who have been through similar experiences.",
    author: "ParentOfWarrior",
    timestamp: "2 hours ago",
    reactions: { heart: 12, thumbsUp: 8, thinking: 2, eyes: 15, hope: 5, hug: 8, grateful: 3 },
    commentCount: 7,
    anonymous: false,
    images: ["/placeholder.svg?height=200&width=300"],
    videos: [],
    community: "pms-support",
    comments: [],
  },
  {
    id: "2",
    caption: "My son was diagnosed with Fragile X Syndrome at 2 years old. We've been learning so much about this condition and how to best support him.",
    author: "FragileXMom",
    timestamp: "1 day ago",
    reactions: { heart: 5, thumbsUp: 3, thinking: 1, eyes: 8, hope: 2, hug: 4, grateful: 6 },
    commentCount: 2,
    anonymous: false,
    images: [],
    videos: [],
    community: "fragile-x-support",
    comments: [],
  },
  {
    id: "3",
    caption: "Today is Angelman Syndrome Awareness Day. Let's raise awareness and share stories of strength and resilience.",
    author: "AngelmanAwareness",
    timestamp: "2 days ago",
    reactions: { heart: 10, thumbsUp: 6, thinking: 3, eyes: 12 },
    commentCount: 5,
    anonymous: true,
    images: [],
    videos: [],
    community: "angelman-support",
    comments: [],
  },
  {
    id: "4",
    caption: "Prader-Willi Syndrome is a rare genetic disorder that affects appetite and weight gain. It's important to understand the signs and symptoms.",
    author: "MedicalResearcher",
    timestamp: "3 days ago",
    reactions: { heart: 8, thumbsUp: 5, thinking: 2, eyes: 10 },
    commentCount: 4,
    anonymous: false,
    images: ["/placeholder.svg?height=200&width=300"],
    videos: [],
    community: "prader-willi-support",
    comments: [],
  },
  {
    id: "5",
    caption: "Our daughter was born with Down Syndrome. It's been a beautiful and challenging journey, filled with love and support from our community.",
    author: "DownSyndromeFamily",
    timestamp: "4 days ago",
    reactions: { heart: 15, thumbsUp: 10, thinking: 5, eyes: 20 },
    commentCount: 10,
    anonymous: false,
    images: ["/placeholder.svg?height=200&width=300"],
    videos: [],
    community: "down-syndrome-support",
    comments: [],
  },
  {
    id: "6",
    caption: "Cystic Fibrosis is a genetic disorder that affects the lungs and digestive system. We're fighting for a cure and supporting those affected.",
    author: "CFWarrior",
    timestamp: "5 days ago",
    reactions: { heart: 20, thumbsUp: 15, thinking: 10, eyes: 30 },
    commentCount: 15,
    anonymous: true,
    images: [],
    videos: [],
    community: "cystic-fibrosis-support",
    comments: [],
  },
  {
    id: "7",
    caption: "Sickle Cell Anemia is a genetic blood disorder. It's important to understand the condition and support those affected.",
    author: "SickleCellAwareness",
    timestamp: "6 days ago",
    reactions: { heart: 12, thumbsUp: 8, thinking: 4, eyes: 15 },
    commentCount: 8,
    anonymous: false,
    images: ["/placeholder.svg?height=200&width=300"],
    videos: [],
    community: "sickle-cell-anemia-support",
    comments: [],
  },
  {
    id: "8",
    caption: "Huntington's Disease is a progressive neurological disorder. It's devastating for families, but we're fighting for research and support.",
    author: "HuntingtonHope",
    timestamp: "7 days ago",
    reactions: { heart: 18, thumbsUp: 12, thinking: 8, eyes: 25 },
    commentCount: 12,
    anonymous: true,
    images: [],
    videos: [],
    community: "huntingtons-disease-support",
    comments: [],
  },
  {
    id: "9",
    caption: "Spinal Muscular Atrophy (SMA) is a rare genetic disorder that affects muscle strength and coordination. It's crucial to understand the condition and support those affected.",
    author: "SMAFamily",
    timestamp: "8 days ago",
    reactions: { heart: 10, thumbsUp: 7, thinking: 3, eyes: 12 },
    commentCount: 6,
    anonymous: false,
    images: ["/placeholder.svg?height=200&width=300"],
    videos: [],
    community: "sma-support",
    comments: [],
  },
  {
    id: "10",
    caption: "Batten Disease is a rare, progressive, and fatal neurological disorder. We're fighting for research and support for those affected.",
    author: "BattenDiseaseAlliance",
    timestamp: "9 days ago",
    reactions: { heart: 25, thumbsUp: 18, thinking: 15, eyes: 40 },
    commentCount: 20,
    anonymous: true,
    images: [],
    videos: [],
    community: "batten-disease-support",
    comments: [],
  },
  {
    id: "11",
    caption: "Tay-Sachs Disease is a rare genetic disorder that affects the nervous system. It's crucial to understand the condition and support those affected.",
    author: "TaySachsConnect",
    timestamp: "10 days ago",
    reactions: { heart: 15, thumbsUp: 10, thinking: 8, eyes: 20 },
    commentCount: 10,
    anonymous: false,
    images: ["/placeholder.svg?height=200&width=300"],
    videos: [],
    community: "tay-sachs-support",
    comments: [],
  },
  {
    id: "12",
    caption: "Gaucher Disease is a rare genetic disorder that affects the body's ability to break down certain fatty substances. It's crucial to understand the condition and support those affected.",
    author: "GaucherDiseaseCommunity",
    timestamp: "11 days ago",
    reactions: { heart: 20, thumbsUp: 15, thinking: 12, eyes: 25 },
    commentCount: 15,
    anonymous: false,
    images: ["/placeholder.svg?height=200&width=300"],
    videos: [],
    community: "gaucher-disease-support",
    comments: [],
  },
  {
    id: "13",
    caption: "Maple Syrup Urine Disease (MSUD) is a rare genetic disorder that affects the body's ability to break down certain amino acids. It's crucial to understand the condition and support those affected.",
    author: "MSUDSupportGroup",
    timestamp: "12 days ago",
    reactions: { heart: 18, thumbsUp: 13, thinking: 10, eyes: 22 },
    commentCount: 13,
    anonymous: false,
    images: ["/placeholder.svg?height=200&width=300"],
    videos: [],
    community: "msud-support",
    comments: [],
  },
  {
    id: "14",
    caption: "Phenylketonuria (PKU) is a rare genetic disorder that affects the body's ability to break down certain amino acids. It's crucial to understand the condition and support those affected.",
    author: "PKULife",
    timestamp: "13 days ago",
    reactions: { heart: 25, thumbsUp: 20, thinking: 15, eyes: 30 },
    commentCount: 20,
    anonymous: false,
    images: ["/placeholder.svg?height=200&width=300"],
    videos: [],
    community: "pku-support",
    comments: [],
  },
  {
    id: "15",
    caption: "This community is for individuals and families affected by various genetic conditions. We share information, support, and resources.",
    author: "GeneralGeneticConditions",
    timestamp: "14 days ago",
    reactions: { heart: 30, thumbsUp: 25, thinking: 20, eyes: 40 },
    commentCount: 25,
    anonymous: false,
    images: [],
    videos: [],
    community: "general-genetic-conditions",
    comments: [],
  },
];

export {} 